# Generated by Django 6.0.2 on 2026-02-19 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financials', '0003_initial'),
        ('properties', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='due',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_reading', to='financials.due'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='properties.property'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='due',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='financials.due'),
        ),
        migrations.AddField(
            model_name='payment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.property'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='properties.property'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='due',
            index=models.Index(fields=['property', 'status', 'due_date'], name='dues_propert_dea04d_idx'),
        ),
        migrations.AddIndex(
            model_name='due',
            index=models.Index(fields=['tenant', 'status'], name='dues_tenant__cd11ef_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['property', 'payment_date'], name='payments_propert_746da0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='payments_tenant__780e71_idx'),
        ),
    ]
