# Generated by Django 6.0.2 on 2026-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duespackage',
            name='icon',
            field=models.CharField(default='💰', max_length=10),
        ),
        migrations.AddField(
            model_name='duespackage',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System categories cannot be deleted'),
        ),
    ]
