# Generated by Django 6.0.2 on 2026-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_duespackage_icon_duespackage_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
