# Generated by Django 6.0.2 on 2026-02-19 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('broken', 'Broken'), ('in_repair', 'In Repair'), ('disposed', 'Disposed')], default='active', max_length=20)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('rent', models.DecimalField(blank=True, decimal_places=2, help_text='Override room-level rent', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('blocked', 'Blocked'), ('under_notice', 'Under Notice')], default='vacant', max_length=20)),
            ],
            options={
                'db_table': 'beds',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'floors',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Sunday, 6=Saturday')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snacks', 'Snacks'), ('dinner', 'Dinner')], max_length=20)),
                ('items', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'food_menus',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('type', models.CharField(choices=[('pg', 'PG'), ('hostel', 'Hostel'), ('co_living', 'Co-Living'), ('flat', 'Flat')], default='pg', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='male', max_length=10)),
                ('total_floors', models.PositiveIntegerField(default=1)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('late_fine_enabled', models.BooleanField(default=False)),
                ('late_fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fine_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Rent'), ('daily', 'Per Day')], default='fixed', max_length=20)),
                ('late_fine_grace_days', models.PositiveIntegerField(default=0)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('default_notice_period', models.PositiveIntegerField(default=30, help_text='Days')),
                ('default_lock_in', models.PositiveIntegerField(default=0, help_text='Months')),
                ('default_agreement_period', models.PositiveIntegerField(default=11, help_text='Months')),
                ('default_rent_cycle_day', models.PositiveIntegerField(default=1, help_text='Day of month')),
                ('curfew_in', models.TimeField(blank=True, null=True)),
                ('curfew_out', models.TimeField(blank=True, null=True)),
                ('kyc_required', models.BooleanField(default=True)),
                ('auto_generate_dues', models.BooleanField(default=True)),
                ('whatsapp_reminders', models.BooleanField(default=False)),
                ('agreement_template', models.TextField(blank=True)),
                ('payment_qr_url', models.URLField(blank=True)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Property Settings',
                'db_table': 'property_settings',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('dormitory', 'Dormitory')], default='single', max_length=20)),
                ('total_beds', models.PositiveIntegerField(default=1)),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('rent_per_bed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('join_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('permissions', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
    ]
