# Generated by Django 6.0.2 on 2026-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_room_address_room_is_available_room_linked_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('blocked', 'Blocked'), ('reserved', 'Reserved'), ('under_notice', 'Under Notice')], default='vacant', max_length=20),
        ),
    ]
