# Generated by Django 6.0.2 on 2026-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_bed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='curfew_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='preferred_tenant_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
