# Generated by Django 4.2.28 on 2026-02-25 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_curfew_time_property_preferred_tenant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('unlisted', 'Unlisted'), ('draft', 'Draft')], default='unlisted', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('video_tour_url', models.URLField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('min_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('enquiries_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('listing_start', models.DateField(blank=True, null=True)),
                ('listing_end', models.DateField(blank=True, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='properties.property')),
            ],
            options={
                'db_table': 'listings',
            },
        ),
    ]
