# Generated by Django 6.0.2 on 2026-02-19 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0003_initial'),
        ('properties', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.room'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['property', 'status'], name='complaints_propert_083040_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['priority'], name='complaints_priorit_2581ce_idx'),
        ),
    ]
