# Generated by Django 6.0.2 on 2026-02-19 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.room'),
        ),
        migrations.AddField(
            model_name='document',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='foodattendance',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='lead',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.staff'),
        ),
        migrations.AddField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='properties.property'),
        ),
        migrations.AddField(
            model_name='oldtenant',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_tenants', to='properties.property'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='properties.room'),
        ),
        migrations.AddField(
            model_name='foodattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_attendance', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['property', 'status'], name='leads_propert_f310fd_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['property', 'status'], name='tenants_propert_39e14d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['phone'], name='tenants_phone_be8eba_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['name'], name='tenants_name_bc4541_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foodattendance',
            unique_together={('tenant', 'date', 'meal_type')},
        ),
    ]
