# Generated by Django 6.0.2 on 2026-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
