# Generated by Django 6.0.2 on 2026-02-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_advance_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
