# Generated by Django 6.0.2 on 2026-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('booking_pending', 'Booking Pending'), ('under_notice', 'Under Notice'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
